version: '3'

networks:
  restaurant-api:

services:
  postgres:
    image: postgres:latest
    container_name: restaurant-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: restaurant-api
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    networks:
      - restaurant-api
